import { Plan, SubscriptionTier, TierLimits } from "@/types";

export const PLANS: Plan[] = [
  {
    id: "free_trial",
    name: "7-Day Free Trial",
    price: 0,
    interval: "trial",
    maxSeats: 1,
    limits: {
      dailyUploads: 2,
      maxFileSizeMb: 5,
      mockExamQuestions: 10,
      flashcardsPerBatch: 5,
      aiRequestsPerDay: 15,
    },
    studyMethods: ["flashcards", "active_recall", "pomodoro"],
    dashboard: "trial",
    highlights: ["2 uploads per day", "3 study methods", "Full dashboard preview"],
  },
  {
    id: "individual",
    name: "Individual",
    price: 4.99,
    interval: "month",
    maxSeats: 1,
    limits: {
      dailyUploads: 20,
      maxFileSizeMb: 15,
      mockExamQuestions: 30,
      flashcardsPerBatch: 15,
      aiRequestsPerDay: 200,
    },
    studyMethods: [
      "flashcards",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
    ],
    dashboard: "individual",
    highlights: ["20 uploads per day", "8 study methods", "Adaptive spaced repetition"],
  },
  {
    id: "family",
    name: "Family",
    price: 19.99,
    interval: "month",
    maxSeats: 5,
    limits: {
      dailyUploads: 40,
      maxFileSizeMb: 20,
      mockExamQuestions: 40,
      flashcardsPerBatch: 20,
      aiRequestsPerDay: 500,
    },
    studyMethods: [
      "flashcards",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
      "mind_map",
      "interleaving",
      "peer_teaching",
    ],
    dashboard: "family",
    highlights: ["5 learner seats", "40 uploads per day", "Household leaderboard"],
  },
  {
    id: "ngo",
    name: "NGO",
    price: 378.99,
    interval: "month",
    maxSeats: 50,
    limits: {
      dailyUploads: 150,
      maxFileSizeMb: 25,
      mockExamQuestions: 50,
      flashcardsPerBatch: 25,
      aiRequestsPerDay: 2000,
    },
    studyMethods: [
      "flashcards",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
      "mind_map",
      "interleaving",
      "peer_teaching",
      "past_paper_drill",
    ],
    dashboard: "ngo",
    highlights: ["50 learner seats", "150 uploads per day", "Outreach impact reporting"],
  },
  {
    id: "school",
    name: "School",
    price: 199.99,
    interval: "month",
    maxSeats: 100,
    limits: {
      dailyUploads: 200,
      maxFileSizeMb: 30,
      mockExamQuestions: 60,
      flashcardsPerBatch: 30,
      aiRequestsPerDay: 5000,
    },
    studyMethods: [
      "flashcards",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
      "mind_map",
      "interleaving",
      "peer_teaching",
      "past_paper_drill",
      "exam_blueprint",
      "cohort_analytics",
    ],
    dashboard: "school",
    highlights: ["100 learner seats", "200 uploads per day", "Class cohort analytics"],
  },
  {
    id: "ministry",
    name: "Ministry",
    price: 599.99,
    interval: "month",
    maxSeats: 500,
    limits: {
      dailyUploads: 1000,
      maxFileSizeMb: 50,
      mockExamQuestions: 80,
      flashcardsPerBatch: 40,
      aiRequestsPerDay: 20000,
    },
    studyMethods: [
      "flashcards",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
      "mind_map",
      "interleaving",
      "peer_teaching",
      "past_paper_drill",
      "exam_blueprint",
      "cohort_analytics",
    ],
    dashboard: "ministry",
    highlights: ["500 learner seats", "1000 uploads per day", "District-wide reporting"],
  },
];

export const DEFAULT_TIER: SubscriptionTier = "free_trial";

export function getPlanByTier(tier: SubscriptionTier): Plan {
  return PLANS.find((p) => p.id === tier) ?? PLANS[0];
}

export function getTierLimits(tier: SubscriptionTier): TierLimits {
  return getPlanByTier(tier).limits;
}

export function isPaidTier(tier: SubscriptionTier): boolean {
  return tier !== "free_trial";
}
