import { Plan, SubscriptionTier, TierLimits } from "@/types";

export const PLANS: Plan[] = [
  {
    id: "free_trial",
    name: "7-Day Free Trial",
    price: 0,
    interval: "trial",
    maxSeats: 1,
    limits: {
      dailyUploads: 50,
      maxFileSizeMb: 25,
      mockExamQuestions: 50,
      flashcardsPerBatch: 25,
      aiRequestsPerDay: 200,
      groqTokenLimit: 250000,
      hasPriorityInference: true,
    },
    studyMethods: [
      "flashcards",
      "quiz",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
    ],
    dashboard: "trial",
    highlights: ["All Pro Features", "Advanced Groq LPU Speed", "Full Study Method Suite"],
  },
  {
    id: "starter_free",
    name: "Starter (Free)",
    price: 0,
    interval: "month",
    maxSeats: 1,
    limits: {
      dailyUploads: 5,
      maxFileSizeMb: 10,
      mockExamQuestions: 5,
      flashcardsPerBatch: 5,
      aiRequestsPerDay: 10,
      groqTokenLimit: 5000,
      hasPriorityInference: false,
    },
    studyMethods: ["flashcards", "quiz", "active_recall", "pomodoro"],
    dashboard: "starter",
    highlights: ["Global Curriculum Access", "Basic Groq LPU Speed", "3 Core Study Methods"],
  },
  {
    id: "pro_scholar",
    name: "Pro Scholar",
    price: 9.99,
    interval: "month",
    maxSeats: 1,
    limits: {
      dailyUploads: 50,
      maxFileSizeMb: 25,
      mockExamQuestions: 50,
      flashcardsPerBatch: 25,
      aiRequestsPerDay: 200,
      groqTokenLimit: 250000,
      hasPriorityInference: true,
    },
    studyMethods: [
      "flashcards",
      "quiz",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
    ],
    dashboard: "individual",
    highlights: ["Advanced Groq LPU (250k Tokens)", "Spaced Repetition AI", "Multilingual Tutor Support"],
  },
  {
    id: "global_elite",
    name: "Global Elite",
    price: 24.99,
    interval: "month",
    maxSeats: 2,
    limits: {
      dailyUploads: 500,
      maxFileSizeMb: 100,
      mockExamQuestions: 100,
      flashcardsPerBatch: 50,
      aiRequestsPerDay: 1000,
      groqTokenLimit: 1000000,
      hasPriorityInference: true,
    },
    studyMethods: [
      "flashcards",
      "quiz",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
      "mind_map",
      "interleaving",
      "peer_teaching",
      "past_paper_drill",
      "exam_blueprint",
    ],
    dashboard: "family",
    highlights: ["Ultra-Fast Inference (1M Tokens)", "All Study Methods", "Priority Global Support"],
  },
  {
    id: "school",
    name: "School",
    price: 199.99,
    interval: "month",
    maxSeats: 100,
    limits: {
      dailyUploads: 1000,
      maxFileSizeMb: 100,
      mockExamQuestions: 100,
      flashcardsPerBatch: 50,
      aiRequestsPerDay: 5000,
      groqTokenLimit: 5000000,
      hasPriorityInference: true,
    },
    studyMethods: [
      "flashcards",
      "quiz",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
      "mind_map",
      "interleaving",
      "peer_teaching",
      "past_paper_drill",
      "exam_blueprint",
      "cohort_analytics",
    ],
    dashboard: "school",
    highlights: ["100 Learner Seats", "Class Analytics", "Unlimited LPU Tutoring"],
  },
  {
    id: "ministry",
    name: "Ministry",
    price: 999.99,
    interval: "month",
    maxSeats: 1000,
    limits: {
      dailyUploads: 5000,
      maxFileSizeMb: 200,
      mockExamQuestions: 200,
      flashcardsPerBatch: 100,
      aiRequestsPerDay: 50000,
      groqTokenLimit: 25000000,
      hasPriorityInference: true,
    },
    studyMethods: [
      "flashcards",
      "quiz",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
      "mind_map",
      "interleaving",
      "peer_teaching",
      "past_paper_drill",
      "exam_blueprint",
      "cohort_analytics",
    ],
    dashboard: "ministry",
    highlights: ["1000 Learner Seats", "National Dashboard", "25M Groq Tokens"],
  },
  {
    id: "ngo",
    name: "NGO",
    price: 378.99,
    interval: "month",
    maxSeats: 50,
    limits: {
      dailyUploads: 500,
      maxFileSizeMb: 50,
      mockExamQuestions: 100,
      flashcardsPerBatch: 50,
      aiRequestsPerDay: 5000,
      groqTokenLimit: 2000000,
      hasPriorityInference: true,
    },
    studyMethods: [
      "flashcards",
      "quiz",
      "active_recall",
      "pomodoro",
      "feynman",
      "spaced_repetition",
      "mock_exam",
      "cornell_notes",
      "blurting",
      "mind_map",
      "interleaving",
      "peer_teaching",
      "past_paper_drill",
    ],
    dashboard: "ngo",
    highlights: ["50 Learner Seats", "Impact Reporting", "2M Groq Tokens"],
  },
];

export const DEFAULT_TIER: SubscriptionTier = "starter_free";

export function getPlanByTier(tier: SubscriptionTier): Plan {
  return PLANS.find((p) => p.id === tier) ?? PLANS[0];
}

export function getTierLimits(tier: SubscriptionTier): TierLimits {
  return getPlanByTier(tier).limits;
}

export function isPaidTier(tier: SubscriptionTier): boolean {
  return tier !== "starter_free" && tier !== "free_trial";
}
